env: "local"
storage_path: "./storage/storage.db"

http:
  address: "localhost:8083"
  timeout: 4s
  idle_timeout: 60s

postgres:
  pool_max: 2
  user: "app"
  password: "secret"
  host: "localhost"
  port: "5432"
  name: "app"